### PR TITLE
fix(store-persistence): wait for pending saves before exiting

### LINKED ISSUE #30: feat(persistence): guarantee state persistence on app exit
There is currently no guarantee that the state is actually saved before exiting.

We should make sure that there is no pending save before calling `app.quit()` in `app.on('window-all-closed')`. I don't know how fast ipcs are, but we should handle the throttling on the main process, this way we can know that there are pending saves.

### PR DESCRIPTION
**Pull request by gautier-lefebvre**
Fixes #30.

Don't merge before #28, I need to write tests.

### CODE REVIEW

File: src/renderer/redux/middlewares/persistState.js [hunk 1]
```diff
@@ -1,24 +1,14 @@
...
  * Redux middleware creator to save the state to a file everytime there is an action.
  *
- * @example const middleware = makeSaveState();
+ * @example
+ * const middleware = makeSaveState();
+ * const store = createStore(reducers, applyMiddleware(middleware));
  */
-export default () => {
-  // Only save the state every second if there are numerous actions being dispatched.
-  const throttledSaveState = throttle(
```
Comment (delphinaubin) [inline src/renderer/redux/middlewares/persistState.js:13]: Why did you remove the `throttle` ? Aren't you afraid to overload the disk by calling a write each time the state change ?

File: src/main/index.js [hunk 2]
```diff
@@ -77,5 +77,14 @@ app.on('activate', () => {
   }
 });
 
+// Emitted when calling app.quit(), or when window-all-closed is not defined.
+app.on('will-quit', (event) => {
+  // If there is a save pending, stop exiting and wait before the save is complete.
+  if (saveStateHandler.currentPromise) {
+    event.preventDefault();
+    saveStateHandler.currentPromise.then(() => app.quit());
```
Comment (delphinaubin) [inline src/main/index.js:87]: Wouldn't be safer to invert the 2 lines above just in case the `saveStateHandler.currentPromise` end after  `event.preventDefault();` but before `saveStateHandler.currentPromise.then(() => app.quit());`

File: src/renderer/redux/middlewares/persistState.js (hunk 1 above)
Comment (gautier-lefebvre) [reply src/renderer/redux/middlewares/persistState.js:13]: I'm throttling on the main process instead, otherwise I cannot know if there are pending saves before exiting.

File: src/main/index.js (hunk 2 above)
Comment (gautier-lefebvre) [reply src/main/index.js:87]: It's single threaded, there are no concurrency issues. In any case, when a promise fulfills, you can call `.then()` a hundred times on it, it will just return the result given to `resolve()`.

File: src/renderer/redux/middlewares/persistState.js (hunk 1 above)
Comment (gautier-lefebvre) [reply src/renderer/redux/middlewares/persistState.js:13]: I'm more concerned about IPC speed but if we start dispatching a 100 actions / s, even the UI is going to be slow ^^

File: src/main/index.js (hunk 2 above)
Comment (maxence-lefebvre) [reply src/main/index.js:87]: `event.preventDefault` is synchronous anyway

File: src/main/state/index.js [hunk 3]
```diff
@@ -36,21 +26,61 @@ function onLoadState(key) {
   return decryptFromFile(key, storeFileEncryptionAlgorithm, storeFilePath);
 }
 
+/**
+ * Create a onSaveState handler.
+ * Used to keep track of pending save requests that must be fulfilled before exiting the app.
+ */
+function OnSaveState() {
```
Comment (maxence-lefebvre) [inline src/main/state/index.js]: why is it capitalized ?

Comment (maxence-lefebvre) [reply src/main/state/index.js]: oh it is a class.
you should add a @constructor (or @class) tag in the jsdoc

File: src/main/state/index.js [hunk 4]
```diff
@@ -36,21 +26,61 @@ function onLoadState(key) {
...
+        if (this.pendingSave) {
+          const tree = this.pendingSave;
+          this.pendingSave = null;
+          return this.onSaveState(tree);
+        }
+
+        return null;
+      });
+
+    return this.currentPromise;
```
Comment (maxence-lefebvre) [inline src/main/state/index.js]: arf this means I will have to make an event to get the storefilepath lol

Comment (gautier-lefebvre) [reply src/main/state/index.js]: Why ? I don't know why you need it renderer-side.

File: src/main/state/index.js (hunk 3 above)
Comment (gautier-lefebvre) [reply src/main/state/index.js]: I added `@class`, eslint didn't like the `@constructor`.

File: src/main/index.js (hunk 2 above)
Comment (delphinaubin) [reply src/main/index.js:87]: Please correct me where i'm wrong :

It's not a concurrency issue but a "non blocking" issue. There is 1 thread but, with asynchronous code, you can't know in which order it will run the code lines.
Yes, you can call a .then to an already resolved promise and it works, but in our case. The promise reference is deleted in the first .then()

So the bad scenario is the following : 
```javascript
// saveStateHandler.currentPromise is defined
if (saveStateHandler.currentPromise) {
  event.preventDefault();
// The saveStateHandler.currentPromise is resolved and the main process decide to run the first .then of it

 .then(() => {
+        this.currentPromise = null;
+   // The promise's reference is deleted
+        if (this.pendingSave) {
+          const tree = this.pendingSave;
+          this.pendingSave = null;
+          return this.onSaveState(tree);
+        }
+
+        return null;
+      });

// The process go back to the first peace of code  : 

saveStateHandler.currentPromise.then(() => app.quit());
// a Uncaught TypeError: Cannot read property 'then' of null is thrown :-S

````

Comment (gautier-lefebvre) [reply src/main/index.js:87]: I see what you mean, and I actually forgot to set the currentPromise to the return value in the `.then()` (recursive). Although, that would not crash as you say because the `if` condition and the `.then` are in the same synchronous block, so we can be sure that they will be executed in the right order.

Comment (gautier-lefebvre) [reply src/main/index.js:87]: Actually I didn't forget to set currentPromise, it's done by the recursivity.

**Review by maxence-lefebvre — APPROVED** [review]
